### ISSUE TITLE
Method not found in obfuscated code

### ISSUE THREAD

**Issue by Nautigsam** [ljsimin/MinecraftJoypadSplitscreenMod#15]
Hey, I have this error when the mod is loading:

    Unable to initialize McGuiHelper.  Unable to continue. java.lang.NoSuchMethodException: net.minecraft.client.gui.GuiScreen.func_146286_b(int, int, int)

It seems that GuiScreen does not have a method like "mouseMovedOrUp".

**Comment by ahickey** [comment]
Make sure that the version of your minecraft source code matches the version of joypad mod you have downloaded and built.  

The name of net.minecraft.client.gui.GuiScreen.func_146286_b was changed in 1.7.2. 

I don't know if newer versions of 1.8 have changed this name but if so, then 
MinecraftJoypadSplitscreenMod/MinecraftJoypadSplitscreenMod/src/com/shiny/joypadmod/helpers/McObfuscationHelper.java will need an update.  Specifically this line where it is looking for that function:

versionNameMap.put("mouseMovedOrUp", new String[] { "func_73879_b", "func_146286_b" });

If you are targeting 1.6.4 then you should get use the 1.6.4 branch of this mod.

**Comment by Nautigsam** [comment]
I use the forge version directly downloaded by gradle as a dependency (in build.gradle) so I suppose I have the right version for the mod, right? (I am on the master branch of the mod). The thing is there is no method in GuiScreen that match this signature (int, int, int), or it's already mapped. I think you know that better than me, but I was just pointing this out. Anyway I commented code so that the corresponding method is not looked for and so no exception is raised. Everything works well for now, but maybe we could find a more persistent way ;)

**Comment by ahickey** [comment]
Thanks
