### ISSUE TITLE
Can't compile on branch 1.8Working

### ISSUE THREAD

**Issue by Nautigsam** [ljsimin/MinecraftJoypadSplitscreenMod#20]
In 08efbdc, the dependencies changed and then I can't compile anymore:
```
Execution failed for task ':deobfMcMCP'.
> Your Access Transformers be broke!
```

I tried to clean everything, even recreating IntelliJ project, it still doesn't work. Do you have any ideas?

**Comment by ahickey** [comment]
Try running ./gradlew setupDecompWorkspace in the same directory as the updated build.grade

If that doesn't work, you can always locally go back to the build.gradle you had before.

**Comment by Nautigsam** [comment]
Okay I did it and also genIntellijRuns. Now it works.
