### ISSUE TITLE
Linux Compatibility 

### ISSUE THREAD

**Issue by ShayBox** [ljsimin/MinecraftJoypadSplitscreenMod#26]
I have a PS3 controller... ubuntu 14.04.3 64x LTS
my controller works natively in most games that support controllers.

and the mod does detect my controller and work, but the default controls don't work at all. they are all weird, and when i try to fix them. it just keeps settings to pos- or something because of motion in the controller. fix this please.

**Comment by Nautigsam** [comment]
Hey, we are working on a new version and this problem should be fixed then. Stay tuned!
