### ISSUE TITLE
Game starts thinking "attacking" set to on 

### ISSUE THREAD

**Issue by ahickey** [ljsimin/MinecraftJoypadSplitscreenMod#3]
For some reason an initial Button press is detected and subsequent Button.isPressed is returning true.  Seems to be reset after pressing the button again.
Seen on Xbox 360 gamepad.

**Comment by Nautigsam** [comment]
Sorry to dig up this old post, but did you find a solution for this? Because I'm still experiencing this issue.

**Comment by ahickey** [comment]
You might have the button set to be a toggle.  When you press it once it continues to respond as pressed automatically until you press it again. 

The toggle feature can be bound to any button, On the in-game joypad menu, when selecting the little circle icon.  

Is that what you are experiencing?

**Comment by Nautigsam** [comment]
Not really, I see this when I use the calibrating menu. The triggers of the controller (wired Xbox controller) have a default value of -1. Like it was indicated in the link @ljsimin posted just above, it seems it is a bug in LWJGL. However, I didn't find any mention of it in any patch notes so I think it's still here. Maybe we should think about a way to bypass this unless you already found a solution.

**Comment by ahickey** [comment]
The pressedOnce boolean in the ControllerInputEvent is designed to handle this scenario.  Basically it should not return a reading for a button or axis unless it has received a pressed event at least once.  

The only time a press event is fired is when you physically press the button on the joystick.  So even if the bug in LWJGL shows that a button or axis is pressed we will not read this value unless there has been a previous press event.  
As others have pointed out in this bug, it stops reporting pressed when the user actually presses and releases at least once. 

The calibration menu should read & report the raw values of the joystick.  We probably want to keep this bug / feature as it is actually what LWJGL is reporting and we want to display as much unfiltered information to the user about their joystick readings here.

In game input events should enforce the "pressed once" event before returning a reading.

**Comment by Nautigsam** [comment]
Maybe I didn't well explained myself. Imagine we have mapped the jump to the trigger. At start there are no problem, like you mentionned it because of the pressedOnce boolean. But when the trigger is pressed, the player jumps so the boolean becomes true right? And then we read continuous jump events because the default value of the axis is -1, and then the player just keeps jumping like a funky rabbit.

**Comment by ahickey** [comment]
The default value of the unpressed axis when initializing LWJGL is -1.  After it is pressed and released once the default reading should be 0 when it is not pressed.  This should be true for the lifetime of the LWJGL object.   
It should not default to -1 after it has been pressed once and is no longer held.  If it is this would likely mean the joystick axis is stuck or has some toggle feature built into the device itself.  I suppose there is the possibility that there is another bug for some working joysticks that report -1 after it has been pressed and released but I have not seen it (with xbox 360 controllers).  

I don't think we should code for the possibility that a user has a deadlocked axis because there would be no real way to determine whether it is physically stuck or they are actually holding it down.

Some axis especially on older joysticks don't naturally rest at 0 and have a small continuous reading even when not pressed.  That should be solvable by the calibration menu.  There is a default threshold set at +/- 0.15 already.

**Comment by Nautigsam** [comment]
Okay I figured it out.
I didn't mention it but I currently work on Linux. I thought this detail was irrelevant because of the portability of Java, Minecraft, LWJGL and so on. The thing is the Linux driver I use detects the triggers as 2 different axis while Windows' one put them on a single one. I think that the Linux way is more logical but anyway, the inputs are different in the end. I will investigate further because it's weird that neither LWJGL or JInput take this in account.

**Comment by ahickey** [comment]
Are you using a xbox 360 controller?
What are the default values of the Left Trigger / Right Trigger at rest (after pressing at least once) ?
Also, what are their values when fully pressed?
Does it go -1 -> +1 (Unpressed -> pressed )?

**Comment by Nautigsam** [comment]
Yes I use a xbox 360 controller and yes, it goes from -1 to 1. I edited my previous comment with my current understanding of the situation.

**Comment by ahickey** [comment]
For solving this issue for Linux I will list some possibilities in order of ease (not sure if all will work)
1) Try changing the deadzone values for your axis using the joypad mod config file or the joypad mod calibration menu and see if you can just make it behave like a button.  If deadzone is set to -1 then maybe anything greater than -1 will cause it to trigger?
2) Try a different joystick driver that uses Windows like mappings for the axis
3) Download a linux joystick modification program that allows you to adjust what values are reported by your joystick
4) Modify the joypad mod source code to allow the user to select whether their joystick uses a -1 at rest axis  and then have code that handles this condition

**Comment by Nautigsam** [comment]
I'm working on the fourth possibility. I'll post a PR asap.

**Comment by Nautigsam** [comment]
I made a fix that adds the possibility for the user to select "single direction axis", I can send a pull request but you must accept #17 before, unless the mod does not work.

**Comment by ahickey** [comment]
Just a follow up that the Xbox one controller in WIndows 10 is reporting a single direction axis.  So this fix couldn't have come at a better time.  Thanks Nautigsam.  I tested your fix and it works perfectly in Windows 10.  We need to get this out soon.
