### ISSUE TITLE
New Xbox one Drivers

### ISSUE THREAD

**Issue by DragonEdge5** [ljsimin/MinecraftJoypadSplitscreenMod#30]
With the windows 10 anniversary update, they fixed the Wireless Xbox one Drivers so the LT and RT are on the same axis like the 360 controllers were. But now the RT won't work in JoypadMod 1.8.9. When I loaded it, The Attack/Destroy was registered as Axis 6+. However it would not work, nor would re-registering it. I check the calibrate option and hitting the RT and LT only moves the Z axis. It has Axis 6 there but nothing happens when the trigger is pressed. I hope there is a way to fix this. I will test the 1.9 version as well but my server is 1.8.9 since there is alot more mods then 1.9

**Comment by DragonEdge5** [comment]
Tested 1.9. Same thing happened

**Comment by aseyotia** [comment]
it does the same for minecraft 1.7.10

**Comment by ahickey** [comment]
Fixed in latest 1.11 check.
