### ISSUE TITLE
Unable to get mod to work with Xbox one controllers

### ISSUE THREAD

**Issue by NPC-112** [ljsimin/MinecraftJoypadSplitscreenMod#32]
I am using vladimircaveman's patched 1.9 version to work on 1.11 from the forums, and I am having issues trying to use my keyboard and mouse on one instance and a wireless Xbox one controller plugged in via USB on the other. I am only able to control one instance at a time like this, even though I should be able to control both. I confirmed that the controller does work, but trying to control two instances with one of them using it doesn't.

My keyboard shows up as a controller because of its special function keys, so I tested the multiple instance interaction by setting the player that was to use the controller to use the keyboard instead(Xbox one controller turned off). I set the attack key to a function key, had both characters on the same world viewing each other. The player using the mouse had their window selected, and could move etc, while the other player would indeed attack whenever i pressed the function key.

Basically, i determined i can't get the setup to work with a wireless Xbox one controller that i have connected through USB. can anyone else confirm if this is the same for them, or offer any help as to how to fix this or why it is happening?

>Edit 1: I should also mention that my system sees my keyboard as multiple devices, attached is an image displaying my keyboards devices. ***(Did not include, don't think its a funny keyboard issue...pretty sure...)***
The mod also recognizes the keyboard as two separate controllers if i enable show all devices, with each only being able to use one of two sets of function keys (one can use media keys, other can use sleep and web etc.) and none of the standard keys, on top of Minecraft recognizing the standard keys and binding them properly in the mouse menu.

>Edit 2: I just tested being able to play with two controllers and not having either player rely on a keyboard/mouse, and it still doesn't work. now i am wondering if it is a limitation imposed by having them plugged in instead of being wireless ( windows sees them separately, and the game does as well) or if it is a problem with the mod itself not being able to capture input from an Xbox one controller when the window isn't the focused window. i'm going to try an older version of the mod and Minecraft and test more.

>Edit 3: Finished testing older versions of Minecraft and the mod, confirmed that i cannot get it to recognize input from the controller if the instance that uses the controller is not in focus. i want to buy a wireless adapter to test if it is because the controller is plugged and using the wired drivers, but am put off by the possibility that it still wont work and would have wasted $25 on one.

***This is copy/pasted from the forum, I am just trying to get as much potential help right now thank you for reading.***

**Comment by ahickey** [comment]
Please use the latest version posted on the forum http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283271-joypad-mod-usb-controller-split-screen-over-350k?page=98
