### ISSUE TITLE
Yellow number at the top left

### ISSUE THREAD

**Issue by methodds** [ljsimin/MinecraftJoypadSplitscreenMod#35]
Hi, 

first of ally thank you for putting the effort in coding this, it works perfectly for me with 1.9 and the version in your forum thread. Using your latest version for 11.2 though, I noticed two issues:
-  I had to manually reconfigure the shoulder buttons, as they were net set up as "attack" and "use block" via default
- As soon as a controller is connected, a yellow "2" appears at the top left screen. This is definitely due to the mod because as soon as I deactivate it, the number appears.

Do you have an idea how to fix this?

**Comment by methodds** [comment]
Just to be precise, I'm currently using the version ````JoypadMod-1.11-13.19.1.2188```` linked here:
https://www.dropbox.com/s/mrcm7g5f526zb6i/JoypadMod-1.11-13.19.1.2188.jar?dl=0

**Comment by ahickey** [comment]
This has been removed in the recent versions.
