### ISSUE TITLE
Not Building in Forge 1.12

### ISSUE THREAD

**Issue by ChimpD** [ljsimin/MinecraftJoypadSplitscreenMod#38]
I tried to build this in MDK 1.12, the repository for Xinput has moved, and I am unable to set the dependency correctly. My build.gradle is below

buildscript {
    repositories {
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.12"
group = "com.shiny.joypadmod"
archivesBaseName = "JoypadMod"

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12-14.21.0.2322"
    runDir = "run"
    mappings = "snapshot_20161220"
}

configurations {
    shade
    compile.extendsFrom shade
}

dependencies {
shade 'org.lwjgl.lwjgl:lwjgl:2.+'
	
shade 'com.github.strikerx3:jxinput:master'
}

jar {
    configurations.shade.each { dep ->
        from(project.zipTree(dep)){
            exclude 'META-INF', 'META-INF/**'
        }
    }
}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

sourceSets {
    main.compileClasspath += configurations.shade
    main.runtimeClasspath += configurations.shade
}

**Comment by ahickey** [comment]
I'm not sure why yours is not working.  I have made similar changes and checked in.  I built and tested it and seems to work from my end.   Did you do gradlew setupdecompworkspace after your build.gradle changes?

I may be using a cached copy of the XInput library so maybe thats why its working for me.  I'll need to see what happens if i remove it.

**Comment by ChimpD** [comment]
I did decomp workspace, that's when i get the error. Cached version sounds right to me. Let me know how your tests go. I'd love a 1.12 build
________________________________

**Comment by ahickey** [comment]
I put up a build at http://bit.ly/2rV9emy

**Comment by ChimpD** [comment]
ty very much, worked for me :)

________________________________
