### ISSUE TITLE
Update to minecraft v1.12.x

### ISSUE THREAD

**Issue by higuita** [ljsimin/MinecraftJoypadSplitscreenMod#41]
HI

Please update this to MC v1.12.x

Thanks

**Comment by higuita** [comment]
i notice that there are commits that referes to 1.12, but i could not find any compiled package to use

**Comment by higuita** [comment]
Found a binary for 1.12 here: 
http://bit.ly/2rV9emy

**Comment by ahickey** [comment]
Link provided does work for 1.12.x http://bit.ly/2rV9emy
