### ISSUE TITLE
Steam Controller, not seeing controller

### ISSUE THREAD

**Issue by eye-sigil** [ljsimin/MinecraftJoypadSplitscreenMod#42]
Not sure how you're checking for xinput devices, but I'm trying to use a steam controller with the steam controller configurator (which emulates an xinput device), and the mod is not seeing it (no controllers found).

Any tips?

**Comment by eye-sigil** [comment]
Isn't workign with a regular controller, either. 1.6.4 version.

**Comment by ahickey** [comment]
The latest versions of Joypad mod have options for 2 different joypad detection methods.  These are accessible in game under Controls -> Advanced -> Legacy detection method.
Legacy detection LWJGL for interacting with controllers and non-legacy uses XInput directly.   You might try switching between the two and restarting Minecraft to see if it works.

1.6.4 is a very old version and support would be similar to legacy detection in the new one.

Also, what OS are you running and what is your regular controller you tried in 2nd comment?

**Comment by eye-sigil** [comment]
Unfortunately, I can't use the latest version; I'm trying to run Tekkit Splitscreen.

I am running Windows 10 Home, and my regular controller was a HoneyBee AIRFLO; a normal xinput device.

**Comment by ahickey** [comment]
Advanced was added in later versions.  

I don't know how to help you except for these tips.

1) always make sure your joypad is plugged in and on prior to starting minecraft
2) try an Xbox controller.  Those seem to have more success
3) try a later joypad mod version.  If it works with your joysticks and you know how to code, you can backport latest changes to 1.6.4.  

No one is working on Joypad mod 1.6.4 in the last 3 years so it is unlikely to be updated again unless someone takes on that task.

**Comment by eye-sigil** [comment]
I found GloSC to fix the problem; if you can, you can update descriptions to tell Steam Input users to use it.

https://github.com/Alia5/GloSC
