### ISSUE TITLE
Triggers only work in menus.

### ISSUE THREAD

**Issue by AustinHasten** [ljsimin/MinecraftJoypadSplitscreenMod#44]
Really wanted to use your mod on 1.12, and the released version is only good up to 1.11, so I built it using gradle. I had one quite major problem though. Using my Afterglow Xbox 360 controller, my left and right triggers do nothing in-game. They do, however, work perfectly fine in menus, which I thought was strange.

Let me know if there's any more information I can provide! Thanks a lot for the wonderful mod.

**Comment by 00Teonis** [comment]
I had the same issue, you need to remap the triggers in the controls menu. Once I remapped LMB and RMB to the triggers again it worked fine.
