### ISSUE TITLE
What does it need to update from 1.12 to 1.13 and 1.14?

### ISSUE THREAD

**Issue by lopez1de** [ljsimin/MinecraftJoypadSplitscreenMod#49]
Is it just changing some meta data? I would really like to this this great mod updated.

**Comment by tonibm19** [comment]
Yay, un update for 1.13 and 1.14 would be nice

**Comment by Avrution** [comment]
Pretty sure the code just needs to be updated for the newer versions, but that is out of my knowledge scope.  Really wishing this was updated as I recently moved to 1.14 and now without controller support

**Comment by lopez1de** [comment]
If you have Steam, you can add Minecraft to it. Then create a Controller Profile for Minecraft and launch it with Steam. Works perfectly.

**Comment by Avrution** [comment]
That is what I ended up doing last night, as much as I hate using Steam for anything
